# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:categories/:title/
relative_permalinks: true

# Setup
title:            daviwil.com
tagline:          'Thoughts on technology, creativity, and life.'
description:      'Thoughts on technology, creativity, and life.'
url:              http://daviwil.com
baseurl:          /

author:
  name:           'David Wilson'
  url:            https://twitter.com/daviwil

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
